# Generated by Django 4.2.23 on 2025-08-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Am', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name Category'),
        ),
        migrations.AlterField(
            model_name='hometranslation',
            name='greetings_2',
            field=models.CharField(max_length=12, verbose_name='Greetings 2'),
        ),
    ]
