# Generated by Django 5.1.1 on 2024-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Am', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='about',
            name='profile_img',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
