# Generated by Django 5.1.1 on 2024-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Am', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(default='C:/Users/User/Documents/main/Imagens/fuckassRaccon.png', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
