# Generated by Django 5.1.1 on 2024-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Am', '0008_about_career_en_about_career_es_about_career_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_1',
            field=models.CharField(max_length=9, verbose_name='Greetings 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1_en',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1_es',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1_fr',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_1_pt',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=9, verbose_name='Greetings 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2_en',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2_es',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2_fr',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings_2_pt',
            field=models.CharField(max_length=9, null=True, verbose_name='Greetings 2'),
        ),
    ]
